name: und_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  cloud_firestore: ^5.6.6
  cloud_functions: ^5.4.0
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  firebase_storage: ^12.4.5
  fl_chart: ^0.71.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  go_router: ^14.8.1
  http: ^1.3.0
  intl: ^0.19.0
  mobile_scanner: ^6.0.7
  data_table_2: ^2.5.18
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  pdf: ^3.11.3
  printing: ^5.12.0
  syncfusion_flutter_charts: ^29.1.0
  table_calendar: ^3.0.9
  uuid: ^4.5.1
  connectivity_plus: ^6.1.3
  shared_preferences: ^2.5.3
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  path: ^1.9.0
  firebase_messaging: 15.2.5
  flutter_local_notifications: ^19.0.0
  logger: ^2.5.0
  share_plus: ^10.1.4
  permission_handler: ^11.4.0
  percent_indicator: ^4.2.3

  meta: any
  collection: any
  logging: any
  google_fonts: ^6.2.1
  local_auth: ^2.3.0
  file_picker: ^10.1.2
dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  mockito: ^5.4.5
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true

dependency_overrides:
  analyzer: ^7.3.0
  meta: ^1.15.0
  collection: ^1.19.0
  test: ^1.25.1
