name: und_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  cloud_firestore: ^5.6.6
  cloud_functions: ^5.4.0
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  firebase_storage: ^12.4.5
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  get_it: ^8.0.3
  go_router: ^15.1.2
  http: ^1.3.0
  intl: ^0.19.0
  mobile_scanner: ^7.0.0
  data_table_2: ^2.5.18
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  pdf: ^3.11.3
  printing: ^5.12.0
  syncfusion_flutter_charts: ^29.1.0
  table_calendar: ^3.0.9
  uuid: ^4.5.1
  connectivity_plus: ^6.1.3
  shared_preferences: ^2.5.3
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  path: ^1.9.0
  firebase_messaging: 15.2.5
  flutter_local_notifications: ^19.0.0
  logger: ^2.5.0
  permission_handler: ^12.0.0+1
  percent_indicator: ^4.2.3
  state_notifier: ^1.0.0
  open_filex: ^4.0.0
  equatable: ^2.0.5
  csv: ^6.0.0
  excel: ^4.0.6
  device_info_plus: 11.4.0
  share_plus: ^11.0.0

  meta: any
  collection: any
  logging: any
  google_fonts: ^6.2.1
  local_auth: ^2.3.0
  file_picker: ^10.1.9
  url_launcher: ^6.3.1
  photo_view: ^0.15.0
  syncfusion_flutter_pdfviewer: ^29.2.4
  flutter_cache_manager: ^3.4.1
  shelf_router: ^1.1.4
  json_annotation: ^4.9.0
  emoji_picker_flutter: ^4.3.0
  shelf: any
  freezed_annotation: ^3.0.0
  speech_to_text: ^7.0.0
  google_generative_ai: ^0.4.7

dev_dependencies:
  custom_lint: ^0.7.5
  flutter_lints: ^5.0.0
  mockito: ^5.4.5
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/fonts/NotoSans-Regular.ttf
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
