enum InventoryMovementType {
  RECEIPT,
  TRANSFER,
  PRODUCTION_CONSUMPTION,
  PRODUCTION_OUTPUT,
  QUALITY_HOLD,
  QUALITY_RELEASE,
  ADJUSTMENT,
  DISPOSAL,
  SHIPPING
}

enum ApprovalStatus { PENDING, APPROVED, REJECTED }

enum MovementItemStatus { IN_TRANSIT, COMPLETED, CANCELLED }

enum QualityStatus { REGULAR, QUARANTINE, APPROVED, REJECTED }

enum LocationType {
  RECEIVING_AREA,
  RAW_MATERIALS,
  PRODUCTION,
  FINISHED_GOODS,
  QUARANTINE,
  SHIPPING
}
