// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRTh_vGkjQdKtZESgBT2NSoIoOuy1Hxgo',
    appId: '1:392085696290:web:343455b6c42aa3e453bf7b',
    messagingSenderId: '392085696290',
    projectId: 'undapp-119cf',
    authDomain: 'undapp-119cf.firebaseapp.com',
    storageBucket: 'undapp-119cf.firebasestorage.app',
    measurementId: 'G-STVWSZV6B0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjHgdTti9q8CpR-h3bUf304mqwpyUPkNI',
    appId: '1:392085696290:android:55c4e1fc17270ca553bf7b',
    messagingSenderId: '392085696290',
    projectId: 'undapp-119cf',
    storageBucket: 'undapp-119cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpREju5tYO1SNa68CVBySKFPbaFPekfo8',
    appId: '1:392085696290:ios:f207a558150a19d853bf7b',
    messagingSenderId: '392085696290',
    projectId: 'undapp-119cf',
    storageBucket: 'undapp-119cf.firebasestorage.app',
    iosBundleId: 'com.example.undApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpREju5tYO1SNa68CVBySKFPbaFPekfo8',
    appId: '1:392085696290:ios:f207a558150a19d853bf7b',
    messagingSenderId: '392085696290',
    projectId: 'undapp-119cf',
    storageBucket: 'undapp-119cf.firebasestorage.app',
    iosBundleId: 'com.example.undApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRTh_vGkjQdKtZESgBT2NSoIoOuy1Hxgo',
    appId: '1:392085696290:web:ad339a730361787a53bf7b',
    messagingSenderId: '392085696290',
    projectId: 'undapp-119cf',
    authDomain: 'undapp-119cf.firebaseapp.com',
    storageBucket: 'undapp-119cf.firebasestorage.app',
    measurementId: 'G-3MN6KBXZ13',
  );
}
